# Generated by Django 6.0.1 on 2026-03-27 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(help_text='Maximum quantity this bin can hold')),
                ('current_load', models.IntegerField(default=0, help_text='Current quantity in bin')),
                ('distance_from_dispatch', models.FloatField(help_text='Distance in meters from dispatch area')),
                ('pick_count', models.IntegerField(default=0, help_text='Number of times items were picked from this bin')),
                ('last_picked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('grn_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(max_length=50, unique=True)),
                ('receipt_date', models.DateField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received by Supervisor'), ('QC_PENDING', 'QC Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('grn_item_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('received_quantity', models.IntegerField()),
                ('accepted_quantity', models.IntegerField(default=0)),
                ('rejected_quantity', models.IntegerField(default=0)),
                ('qc_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('qc_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='inbound_trans',
            fields=[
                ('inbound_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('po_id', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PLANNED', 'Putaway Planned'), ('COMPLETED', 'Completed')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='outbound_trans',
            fields=[
                ('outbound_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PLANNED', 'Pick Planned'), ('DISPATCHED', 'Dispatched')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent to Vendor'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('pr_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('requested_quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MANAGER_APPROVED', 'Manager Approved'), ('FINANCE_PENDING', 'Finance Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rack_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('shelf_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('movement_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('STOCK_ADDITION', 'Stock Addition'), ('STOCK_REMOVAL', 'Stock Removal'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('reference', models.CharField(blank=True, help_text='Reference document (e.g., GRN-001, PO-001)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('zone_type', models.CharField(choices=[('RECEIVING', 'Receiving'), ('STORAGE', 'Storage'), ('PICKING', 'Picking'), ('SHIPPING', 'Shipping'), ('RETURNS', 'Returns')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('asn_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('asn_number', models.CharField(max_length=50, unique=True)),
                ('shipment_date', models.DateField()),
                ('expected_arrival_date', models.DateField()),
                ('actual_arrival_date', models.DateField(blank=True, null=True)),
                ('vehicle_num', models.CharField(max_length=13)),
                ('driver_name', models.CharField(max_length=25)),
                ('driver_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asns', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ASNItem',
            fields=[
                ('asn_item_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('expected_quantity', models.IntegerField()),
                ('shipped_quantity', models.IntegerField()),
                ('received_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.asn')),
            ],
        ),
    ]
