# Generated by Django 6.0.1 on 2026-03-27 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asn_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='grn',
            name='asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='Inventory.asn'),
        ),
        migrations.AddField(
            model_name='grn',
            name='qc_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grn',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.grn'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='inbound_trans',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='Inventory.bin'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='outbound_trans',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='grn',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='Inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='asn',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='Inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_prs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='products.product'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='Inventory.purchaserequest'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='Inventory.rack'),
        ),
        migrations.AddField(
            model_name='bin',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='Inventory.shelf'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='Inventory.bin'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product'),
        ),
        migrations.AddField(
            model_name='rack',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='Inventory.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='asnitem',
            unique_together={('asn', 'product')},
        ),
        migrations.AddIndex(
            model_name='grnitem',
            index=models.Index(fields=['qc_status'], name='Inventory_g_qc_stat_f2a03c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'quantity'], name='Inventory_i_product_d7cfa4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['bin', 'quantity'], name='Inventory_i_bin_id_400944_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'bin')},
        ),
        migrations.AddIndex(
            model_name='grn',
            index=models.Index(fields=['status'], name='Inventory_g_status_bfb526_idx'),
        ),
        migrations.AddIndex(
            model_name='grn',
            index=models.Index(fields=['receipt_date'], name='Inventory_g_receipt_7dc564_idx'),
        ),
        migrations.AddIndex(
            model_name='asn',
            index=models.Index(fields=['status'], name='Inventory_a_status_c6c4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='asn',
            index=models.Index(fields=['expected_arrival_date'], name='Inventory_a_expecte_93959a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status'], name='Inventory_p_status_afbef0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_at'], name='Inventory_p_created_a2d5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='Inventory_p_status_525df8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_at'], name='Inventory_p_created_5c2087_idx'),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['current_load', 'capacity'], name='Inventory_b_current_e7d667_idx'),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['distance_from_dispatch'], name='Inventory_b_distanc_5bf5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['pick_count'], name='Inventory_b_pick_co_c7c8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-created_at'], name='Inventory_s_product_a2af08_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='Inventory_s_movemen_1c844e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='Inventory_s_referen_63d2e9_idx'),
        ),
    ]
